"""add review

Revision ID: c24b514928d3
Revises: ea13358a1ca2
Create Date: 2024-11-03 21:28:57.947243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24b514928d3'
down_revision = 'ea13358a1ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reviews_items_id_items', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    op.drop_column('reviews', 'items_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('items_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_items_id_items', 'reviews', 'items', ['items_id'], ['id'])
    op.drop_column('reviews', 'item_id')
    # ### end Alembic commands ###
